version: '2'

services:
    caliper:
        container_name: caliper
        tty: true
        image: hyperledger/caliper:0.4.2
        command: launch manager
        environment:
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        volumes:
          - /var/run/:/host/var/run/
          - ./benchmarks:/hyperledger/caliper/workspace/benchmarks
          - ./networks:/hyperledger/caliper/workspace/networks
          - ./workload:/hyperledger/caliper/workspace/workload
          - ./caliper.yaml:/hyperledger/caliper/workspace/caliper.yaml
          - ../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp:/hyperledger/caliper/workspace/msp
          - ../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml:/hyperledger/caliper/workspace/connection-org1.yaml
        network_mode: "host"

